### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by EthanUphoff** [UMM-CSci-4453-S19/final-project-drop_more_tables#1]
Here are the following things we have to do still:
- [x] put stats in pokemon output
- [x] put types in pokemon output
- [x] create/add custom pokemon tables for each user (procedure)
- [x] add moves command to look up all moves a pokemon can have
- [x] add type efficiencies
- [x] add alolan and mega forms
- [x] view custom pokemon 
- [x] limit number of moves 
- [x] make presentation
